
get http://localhost:3002/parent/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhMWY0YmRjZjZjZGMwMGE4ODczMjciLCJpYXQiOjE2ODM2NTYzOTgsImV4cCI6MTY4MzkxNTU5OH0.o-XHcTC9liEEOyM7xT57nA9EMarQefCRccn8M6xNt1Q
###
get http://localhost:3002/parent/details/643ef2b8b782fde616701019
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhMWY0YmRjZjZjZGMwMGE4ODczMjciLCJpYXQiOjE2ODM2NTYzOTgsImV4cCI6MTY4MzkxNTU5OH0.o-XHcTC9liEEOyM7xT57nA9EMarQefCRccn8M6xNt1Q
###
get http://localhost:3002/parent/teacherCours/645982c630730a05c2a28f36/643ef2b8b782fde616701019
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhMWY0YmRjZjZjZGMwMGE4ODczMjciLCJpYXQiOjE2ODM2NTYzOTgsImV4cCI6MTY4MzkxNTU5OH0.o-XHcTC9liEEOyM7xT57nA9EMarQefCRccn8M6xNt1Q
###
get http://localhost:3002/parent/teacherProfile/645982c630730a05c2a28f36
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhMWY0YmRjZjZjZGMwMGE4ODczMjciLCJpYXQiOjE2ODM2NTYzOTgsImV4cCI6MTY4MzkxNTU5OH0.o-XHcTC9liEEOyM7xT57nA9EMarQefCRccn8M6xNt1Q
###
get http://localhost:3002/parent/myProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhMWY0YmRjZjZjZGMwMGE4ODczMjciLCJpYXQiOjE2ODM2NTYzOTgsImV4cCI6MTY4MzkxNTU5OH0.o-XHcTC9liEEOyM7xT57nA9EMarQefCRccn8M6xNt1Q