get http://localhost:3002/teacher/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDU5ODJjNjMwNzMwYTA1YzJhMjhmMzYiLCJpYXQiOjE2ODQ1MjczODAsImV4cCI6MTY4NDc4NjU4MH0.gDiDS3p6Wu85NjLP-D7T1lFvJx7gVNq7PX1DZilxOuc
###
get http://localhost:3002/teacher/parentsList/643ef2b8b782fde616701019
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDU5ODJjNjMwNzMwYTA1YzJhMjhmMzYiLCJpYXQiOjE2ODQ1MjczODAsImV4cCI6MTY4NDc4NjU4MH0.gDiDS3p6Wu85NjLP-D7T1lFvJx7gVNq7PX1DZilxOuc
###
get http://localhost:3002/teacher/cours/643ef2b8b782fde616701019
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc3OWI4M2Q3N2ZiZWVhM2NkOTkyMWMiLCJpYXQiOjE2ODU3OTA2NjEsImV4cCI6MTY4NjA0OTg2MX0.nkTUcvcCRjSJW6ZLwamXRgmAek-YafbpgkVywctiz_w
###
post http://localhost:3002/teacher/creatCours/643ef2b8b782fde616701019
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc3OWI4M2Q3N2ZiZWVhM2NkOTkyMWMiLCJpYXQiOjE2ODU3OTA2NjEsImV4cCI6MTY4NjA0OTg2MX0.nkTUcvcCRjSJW6ZLwamXRgmAek-YafbpgkVywctiz_w

{
    "content":{"text":"exercice 5 page 30"},
    "toDoBefore":"2023-05-06T09:00:00.000Z"
}
###
post http://localhost:3002/signup
Content-Type: application/json

{
"cin": 12345671,
"nom":"messaoudi",
"prenom":"eyya",
"tel":25620759,
"email":"aa@gmaill.com",
"password":"#Asma12345",
"confirmPass":"#Asma12345"
}
###
post http://localhost:3002/login
Content-Type: application/json

{
    "cin":"12345680",
    "password":"#Asma12345"
}
###
get http://localhost:3002/teacher/parentProfile/645a1f4bdcf6cdc00a887327
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDU5ODJjNjMwNzMwYTA1YzJhMjhmMzYiLCJpYXQiOjE2ODQ1MjczODAsImV4cCI6MTY4NDc4NjU4MH0.gDiDS3p6Wu85NjLP-D7T1lFvJx7gVNq7PX1DZilxOuc
###
get http://localhost:3002/teacher/myProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDU5ODJjNjMwNzMwYTA1YzJhMjhmMzYiLCJpYXQiOjE2ODUxMTk2MDEsImV4cCI6MTY4NTM3ODgwMX0.s3n2a_RnjOrDfKjblKZbF4coDdFqwxkMtRnxt0Xuo5c
###
get http://localhost:3002/teacher/discussion/64779bddd77fbeea3cd9d830
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc3OWI4M2Q3N2ZiZWVhM2NkOTkyMWMiLCJpYXQiOjE2ODU3OTA2NjEsImV4cCI6MTY4NjA0OTg2MX0.nkTUcvcCRjSJW6ZLwamXRgmAek-YafbpgkVywctiz_w
###
put http://localhost:3002/teacher/changeText/647cbfac849e16c46191ad8a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc3OWI4M2Q3N2ZiZWVhM2NkOTkyMWMiLCJpYXQiOjE2ODU3OTA2NjEsImV4cCI6MTY4NjA0OTg2MX0.nkTUcvcCRjSJW6ZLwamXRgmAek-YafbpgkVywctiz_w
Content-Type: application/json

{
    "newText":"exercice 1 page 39"
}
###
get http://localhost:3002/teacher/getMatiere
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdiMDU5Mjc5Njc3ZTNjZjVmYzMzYzEiLCJpYXQiOjE2ODU5MDk4MDIsImV4cCI6MTY4NjE2OTAwMn0.YINvAP8ijNS4EtrYt_QC5_DMI1thh-bzgvucW2It_vY
###
POST http://localhost:3002/teacher/addAreply/647cc813849e16c46191aec5/647d9154779b27d984f6135e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdiMDU5Mjc5Njc3ZTNjZjVmYzMzYzEiLCJpYXQiOjE2ODU5MDk4MDIsImV4cCI6MTY4NjE2OTAwMn0.YINvAP8ijNS4EtrYt_QC5_DMI1thh-bzgvucW2It_vY
Content-Type: application/json

{
    "content":"kteb math ?"
}