
get http://localhost:3002/parent/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhMWY0YmRjZjZjZGMwMGE4ODczMjciLCJpYXQiOjE2ODM2NTYzOTgsImV4cCI6MTY4MzkxNTU5OH0.o-XHcTC9liEEOyM7xT57nA9EMarQefCRccn8M6xNt1Q
###
get http://localhost:3002/parent/details/643ef2b8b782fde616701019
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhYjM1N2YxMmIxOTFlZGE4YTJhZTciLCJpYXQiOjE2ODM5MDk1NjYsImV4cCI6MTY4NDE2ODc2Nn0.ZmcPWeWS_AwYMjKv0npPRnkVeJyzMKWeSoKvcEJV7ew
###
get http://localhost:3002/parent/teacherCours/645982c630730a05c2a28f36/643ef2b8b782fde616701019
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhYjM1N2YxMmIxOTFlZGE4YTJhZTciLCJpYXQiOjE2ODM5MDk1NjYsImV4cCI6MTY4NDE2ODc2Nn0.ZmcPWeWS_AwYMjKv0npPRnkVeJyzMKWeSoKvcEJV7ew
###
get http://localhost:3002/parent/teacherProfile/645982c630730a05c2a28f36
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhMWY0YmRjZjZjZGMwMGE4ODczMjciLCJpYXQiOjE2ODM2NTYzOTgsImV4cCI6MTY4MzkxNTU5OH0.o-XHcTC9liEEOyM7xT57nA9EMarQefCRccn8M6xNt1Q
###
get http://localhost:3002/parent/myProfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhYjM1N2YxMmIxOTFlZGE4YTJhZTciLCJpYXQiOjE2ODQxODYwODUsImV4cCI6MTY4NDQ0NTI4NX0.1N5G4LnqxI9MggPfueU5oH6U1W2Hn6XZ34IsJEvrvqg
###
get http://localhost:3002/parent/discussion/645982c630730a05c2a28f36
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhYjM1N2YxMmIxOTFlZGE4YTJhZTciLCJpYXQiOjE2ODQ1MjUyNTksImV4cCI6MTY4NDc4NDQ1OX0.hXpMoK1EsR2G3GRvMp68lCbogc1BXsBzcEuO05_Y9s8
###
post http://localhost:3002/parent/sendMessage/645982c630730a05c2a28f36
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVhYjM1N2YxMmIxOTFlZGE4YTJhZTciLCJpYXQiOjE2ODM5MDk1NjYsImV4cCI6MTY4NDE2ODc2Nn0.ZmcPWeWS_AwYMjKv0npPRnkVeJyzMKWeSoKvcEJV7ew
Content-Type: application/json

{
    "contenu" :"hello"
}
###
post http://localhost:3002/changePassword
Content-Type: application/json

{
    "email":"dakhliferdaous4@gmail.com"
}